wicd-gtk &
ck-launch-session dbus-launch devmon --unmount-on-exit &
feh --bg-scale /home/echo/pictures/dwm-bg01.png &
conky | while read -r; do xsetroot -name "$REPLY"; done &
gnome-sound-applet &
batti &
dwm 
